updated features
priyam1103/neog-videocomp pull request #1
Opened 2021-05-07 18:31 UTC by priyam1103

2021-05-09 05:11 UTC, theshivamverma requested changes

2021-05-09 05:11 UTC, theshivamverma commented on components/UpdateData.js
> +  const { updateState } = useContext(GlobalContext);
try to make a custom hook in your context and use that to get data from context

2021-05-09 05:11 UTC, theshivamverma commented on context/AppReducer.js
> +      console.log(action.payload.dislikes);
remove console logs from all places

2021-05-09 05:21 UTC, theshivamverma commented
please provide the deployed url in PR, try using camelCase naming for your variables and functions, it improves code readability.
remove extra spacing, unused code and comments.

2021-05-10 11:10 UTC, Akshay-Laxmipathi commented
Add some margin to your pill shaped filter buttons...the "all" button is partly enclosed in the sidebar space

2021-05-27 12:13 UTC, merged